### ISSUE TITLE
leximaなどによる改行で範囲が壊れる

### ISSUE THREAD

**Issue by uga-rosa** [uga-rosa/denippet.vim#8]
leximaなどのプラグインを使い改行を入力すると、カーソル後ろにも改行が入ることがある。これをtabstopでの入力中に実行すると、この改行が認識されず（rangeに含まれない、extmarkのend_right_gravityを越えているぽい）、範囲が壊れる

**Comment by uga-rosa** [comment]
とりあえず調査として、jumpableNode以外にもextmarkを付けてrangeを監視してみる。
これで他の範囲も壊れるならお手上げ、更新範囲の検知は別の方法を使うか、leximaをやめる。

**Comment by Shougo** [comment]
lexima 対応大変そう

**Comment by uga-rosa** [comment]
これ、nvim-insxだと再現しなかったので一旦しおづけ
